export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';

export const FETCH_ISSUES_PENDING = 'FETCH_ISSUES_PENDING';
export const FETCH_ISSUES_REJECTED = 'FETCH_ISSUES_REJECTED';
export const FETCH_ISSUES_FULFILLED = 'FETCH_ISSUES_FULFILLED';

export const FETCH_REPOS_PENDING = 'FETCH_REPOS_PENDING';
export const FETCH_REPOS_REJECTED = 'FETCH_REPOS_REJECTED';
export const FETCH_REPOS_FULFILLED = 'FETCH_REPOS_FULFILLED';

export const SET_PER_PAGE_COUNT = 'SET_PER_PAGE_COUNT';
export const SET_PREV_PAGE = 'SET_PREV_PAGE';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';

